services:
    mysql:
        image: mysql:oraclelinux9
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: chatdb
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        ports:
            - "3307:3306"
        volumes:
            - "mysql-data:/var/lib/mysql"
    rabbitmq:
        image: rabbitmq:4-management
        ports:
            - "5672:5672"
            - "15672:15672"
    auth:
        image: neerajsurjaye/auth
        ports:
            - 5757:5757
        environment:
            USER: SPEC
            PORT: 5757
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_CONNECTION: 127.0.0.1
            MYSQL_DB: chatdb
            MYSQL_PORT: 3307
            JWT_SECRET: SPECSJWTSECRET

volumes:
    mysql-data:
