services:
    mysql:
        image: mysql:oraclelinux9
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: chatdb
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        ports:
            - "3307:3306"
        volumes:
            - "mysql-data:/var/lib/mysql"
    rabbitmq:
        image: rabbitmq:4-management
        ports:
            - "5672:5672"
            - "15672:15672"
    auth:
        image: neerajsurjaye/auth:latest
        # ports:
        # - 5757:5757
        environment:
            USER: SPEC
            PORT: 5757
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_CONNECTION: mysql
            MYSQL_DB: chatdb
            # Port inside container
            MYSQL_PORT: 3306
            JWT_SECRET: SPECSJWTSECRET

    gateway:
        image: neerajsurjaye/gateway:latest
        ports:
            - 5758:5758
        environment:
            AUTH_URL: http://auth:5757
            RABBIT_URL: amqp://rabbitmq:5672
            PORT: 5758
            ARCHIVER_URL: http://archiver:5759

    archiver:
        image: neerajsurjaye/archiver:latest
        # ports:
        # - 5759:5759
        environment:
            RABBIT_URL: amqp://rabbitmq:5672
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_CONNECTION: mysql
            MYSQL_DB: chatdb
            MYSQL_PORT: 3306
            PORT: 5759
volumes:
    mysql-data:
