services:
    postgres:
        image: postgres:16.9
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: schatdb
        ports:
            - "5432:5432"
        volumes:
            - "postgres-data:/var/lib/postgresql/data"
    rabbitmq:
        image: rabbitmq:4-management
        ports:
            - "5672:5672"
            - "15672:15672"
volumes:
    postgres-data:
