services:
    mysql:
        image: mysql:oraclelinux9
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: chatdb
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        ports:
            - "3307:3306"
        volumes:
            - "mysql-data:/var/lib/mysql"
    rabbitmq:
        image: rabbitmq:4-management
        ports:
            - "5672:5672"
            - "15672:15672"
volumes:
    mysql-data:
