apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth

spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 2

    template:
        metadata:
            labels:
                app: auth

        spec:
            containers:
                - name: auth

                  image: neerajsurjaye/auth:latest
                  imagePullPolicy: Never

                  ports:
                      - containerPort: 5757
                  envFrom:
                      - configMapRef:
                            name: auth-configmap
