apiVersion: v1
kind: ConfigMap
metadata:
    name: auth-configmap
data:
    USER: SPEC
    PORT: "5757"
    MYSQL_USER: admin
    # My sql host
    MYSQL_CONNECTION: schat-db.cyniuw0qkokl.us-east-1.rds.amazonaws.com
    MYSQL_DB: chatdb
    MYSQL_PORT: "3306"
