apiVersion: apps/v1
kind: Deployment
metadata:
    name: archiver

spec:
    replicas: 1
    selector:
        matchLabels:
            app: archiver
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 2

    template:
        metadata:
            labels:
                app: archiver

        spec:
            containers:
                - name: archiver

                  image: neerajsurjaye/archiver:latest
                  imagePullPolicy: Never

                  ports:
                      - containerPort: 5759

                  envFrom:
                      - configMapRef:
                            name: archiver-configmap
