apiVersion: v1
kind: Service
metadata:
    name: rabbitmq-service
spec:
    type: NodePort
    selector:
        app: rabbitmq
    ports:
        - name: "rabbitmq"
          port: 5672
          targetPort: 5672
        - name: "web-ui"
          port: 15672
          targetPort: 15672
          nodePort: 32672
