apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mysql-mystatefulset
spec:
    selector:
        matchLabels:
            app: mysql
    serviceName: mysql-service
    replicas: 1
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                - name: mysql
                  image: mysql:oraclelinux9
                  ports:
                      - containerPort: 3306
                  volumeMounts:
                      - name: mysql-volume
                        mountPath: /var/lib/mysql
                  envFrom:
                      - configMapRef:
                            name: mysql-configmap

    volumeClaimTemplates:
        - metadata:
              name: mysql-volume
          spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                  requests:
                      storage: 1Gi
